version: '3.8'

services:
  db:
    image: postgres:15
    container_name: userdb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: internal_transfer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d internal_transfer"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
